insert into companies (nombre, nacionalidad) values ('Stehr Inc', 'Slovenia');
insert into companies (nombre, nacionalidad) values ('Langosh LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Parker, Ankunding and Wuckert', 'Tanzania');
insert into companies (nombre, nacionalidad) values ('Schaefer and Sons', 'Argentina');
insert into companies (nombre, nacionalidad) values ('Dietrich, Towne and Zemlak', 'Costa Rica');
insert into companies (nombre, nacionalidad) values ('Macejkovic-Sawayn', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Walter-Funk', 'France');
insert into companies (nombre, nacionalidad) values ('Schroeder Group', 'Japan');
insert into companies (nombre, nacionalidad) values ('Shields-Johns', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Ullrich-Kemmer', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Rice-Kassulke', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Dickinson-Bogisich', 'China');
insert into companies (nombre, nacionalidad) values ('Gaylord-Pacocha', 'United Kingdom');
insert into companies (nombre, nacionalidad) values ('Gibson, Brakus and Wilderman', 'France');
insert into companies (nombre, nacionalidad) values ('Stroman LLC', 'Peru');
insert into companies (nombre, nacionalidad) values ('Moen-Lowe', 'Norway');
insert into companies (nombre, nacionalidad) values ('Gleichner-Reinger', 'Belarus');
insert into companies (nombre, nacionalidad) values ('Gottlieb and Sons', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Schmeler Inc', 'Iran');
insert into companies (nombre, nacionalidad) values ('Connelly-Moore', 'China');
insert into companies (nombre, nacionalidad) values ('Crona Inc', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Murray-Keebler', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Jones-Farrell', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Maggio-Breitenberg', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Casper-Fisher', 'Chile');
insert into companies (nombre, nacionalidad) values ('Douglas-Balistreri', 'Armenia');
insert into companies (nombre, nacionalidad) values ('Blick-Sawayn', 'Namibia');
insert into companies (nombre, nacionalidad) values ('Corkery-Kshlerin', 'Poland');
insert into companies (nombre, nacionalidad) values ('Upton and Sons', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Jaskolski, Bradtke and Waelchi', 'China');
insert into companies (nombre, nacionalidad) values ('Kuvalis, Haag and McCullough', 'France');
insert into companies (nombre, nacionalidad) values ('Strosin, Kuhn and Maggio', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Sawayn, Littel and Maggio', 'China');
insert into companies (nombre, nacionalidad) values ('Towne LLC', 'Poland');
insert into companies (nombre, nacionalidad) values ('Veum, Hills and Stehr', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Gusikowski Inc', 'Greece');
insert into companies (nombre, nacionalidad) values ('Upton, Halvorson and Conroy', 'Pakistan');
insert into companies (nombre, nacionalidad) values ('Willms Inc', 'Democratic Republic of the Congo');
insert into companies (nombre, nacionalidad) values ('Stamm, Boehm and Brown', 'Kuwait');
insert into companies (nombre, nacionalidad) values ('Abernathy-Deckow', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Williamson, Reichel and Bergstrom', 'China');
insert into companies (nombre, nacionalidad) values ('Shields, Cartwright and Pagac', 'Poland');
insert into companies (nombre, nacionalidad) values ('Weissnat and Sons', 'South Korea');
insert into companies (nombre, nacionalidad) values ('Weimann, Dach and Torp', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Upton Group', 'China');
insert into companies (nombre, nacionalidad) values ('Keebler Group', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Kuvalis Inc', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Kilback LLC', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Reinger, O''Connell and Christiansen', 'Madagascar');
insert into companies (nombre, nacionalidad) values ('Nikolaus-Towne', 'Mauritius');
insert into companies (nombre, nacionalidad) values ('Harvey-Stroman', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Jaskolski, Parker and Wolff', 'China');
insert into companies (nombre, nacionalidad) values ('Klein, Volkman and Brown', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Kertzmann, Paucek and Crona', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Torphy, Blanda and Boehm', 'Tunisia');
insert into companies (nombre, nacionalidad) values ('Barrows, Reilly and Blick', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Smitham, Stroman and Dickens', 'China');
insert into companies (nombre, nacionalidad) values ('Denesik Group', 'France');
insert into companies (nombre, nacionalidad) values ('Wintheiser, Bergstrom and Rosenbaum', 'Moldova');
insert into companies (nombre, nacionalidad) values ('Bruen Inc', 'Russia');
insert into companies (nombre, nacionalidad) values ('Watsica-Lemke', 'Russia');
insert into companies (nombre, nacionalidad) values ('Schulist-Bechtelar', 'Poland');
insert into companies (nombre, nacionalidad) values ('Johnson, Reinger and Abernathy', 'Germany');
insert into companies (nombre, nacionalidad) values ('Schimmel Inc', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Veum-Tillman', 'Poland');
insert into companies (nombre, nacionalidad) values ('Maggio, Cruickshank and Weber', 'China');
insert into companies (nombre, nacionalidad) values ('Zulauf, Barrows and Dare', 'China');
insert into companies (nombre, nacionalidad) values ('Deckow-Rodriguez', 'Zimbabwe');
insert into companies (nombre, nacionalidad) values ('Spinka LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Bahringer LLC', 'France');
insert into companies (nombre, nacionalidad) values ('Gibson Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Hilll and Sons', 'Peru');
insert into companies (nombre, nacionalidad) values ('Upton, Kilback and Labadie', 'Russia');
insert into companies (nombre, nacionalidad) values ('Hane-Bosco', 'Philippines');
insert into companies (nombre, nacionalidad) values ('DuBuque Group', 'China');
insert into companies (nombre, nacionalidad) values ('Collins, Emmerich and Parisian', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Macejkovic-Mills', 'Argentina');
insert into companies (nombre, nacionalidad) values ('Kuhn, Jacobson and Schmitt', 'Bolivia');
insert into companies (nombre, nacionalidad) values ('Runolfsdottir, Prosacco and Stark', 'Yemen');
insert into companies (nombre, nacionalidad) values ('Larkin, Hansen and Schaden', 'Japan');
insert into companies (nombre, nacionalidad) values ('Lindgren, Howell and Runolfsson', 'Peru');
insert into companies (nombre, nacionalidad) values ('Dibbert-Grant', 'Australia');
insert into companies (nombre, nacionalidad) values ('Conn, Kling and Rogahn', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Altenwerth LLC', 'Cuba');
insert into companies (nombre, nacionalidad) values ('Spencer Group', 'China');
insert into companies (nombre, nacionalidad) values ('Rippin-Goyette', 'Cuba');
insert into companies (nombre, nacionalidad) values ('Gerlach, Terry and Cronin', 'France');
insert into companies (nombre, nacionalidad) values ('Shields LLC', 'Poland');
insert into companies (nombre, nacionalidad) values ('Considine and Sons', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Hoeger, Collier and Hessel', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Connelly-Nikolaus', 'China');
insert into companies (nombre, nacionalidad) values ('Cummerata, Hammes and Goyette', 'China');
insert into companies (nombre, nacionalidad) values ('Hilpert Group', 'Russia');
insert into companies (nombre, nacionalidad) values ('Batz, Moen and Robel', 'Moldova');
insert into companies (nombre, nacionalidad) values ('Crona and Sons', 'Latvia');
insert into companies (nombre, nacionalidad) values ('Koss, Kautzer and Bogisich', 'Poland');
insert into companies (nombre, nacionalidad) values ('Purdy Group', 'Haiti');
insert into companies (nombre, nacionalidad) values ('Wolff Inc', 'Poland');
insert into companies (nombre, nacionalidad) values ('Wiegand, Lehner and Hackett', 'Russia');
insert into companies (nombre, nacionalidad) values ('Kihn-Dickinson', 'Madagascar');
insert into companies (nombre, nacionalidad) values ('Becker and Sons', 'Serbia');
insert into companies (nombre, nacionalidad) values ('Gulgowski-MacGyver', 'Albania');
insert into companies (nombre, nacionalidad) values ('Mitchell Group', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Heidenreich Group', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Klein-Dickens', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Reichel, Adams and Walsh', 'Malaysia');
insert into companies (nombre, nacionalidad) values ('McLaughlin, Dickens and Wolf', 'China');
insert into companies (nombre, nacionalidad) values ('Windler and Sons', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Leffler-D''Amore', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Labadie-Langosh', 'Poland');
insert into companies (nombre, nacionalidad) values ('Gaylord Inc', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Littel, Trantow and Abernathy', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Gleichner-Kiehn', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Kerluke-Jones', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Schinner-Prosacco', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Olson LLC', 'Russia');
insert into companies (nombre, nacionalidad) values ('Lowe-Rogahn', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Marvin-Hoppe', 'Guatemala');
insert into companies (nombre, nacionalidad) values ('Harris, Stehr and Terry', 'China');
insert into companies (nombre, nacionalidad) values ('O''Conner, Wisozk and Connelly', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Gislason Group', 'South Korea');
insert into companies (nombre, nacionalidad) values ('Barton Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Stamm-Jerde', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Schinner, Rohan and Bechtelar', 'United States');
insert into companies (nombre, nacionalidad) values ('Smith, Schuppe and Mohr', 'China');
insert into companies (nombre, nacionalidad) values ('Tillman and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Greenholt, Lemke and Considine', 'China');
insert into companies (nombre, nacionalidad) values ('Fahey-Thiel', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Runolfsdottir, Bednar and Rippin', 'Hungary');
insert into companies (nombre, nacionalidad) values ('Hagenes, Pfeffer and Haley', 'Russia');
insert into companies (nombre, nacionalidad) values ('Pfeffer, Franecki and Maggio', 'Moldova');
insert into companies (nombre, nacionalidad) values ('Weber, Mitchell and Pouros', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Pagac-Bauch', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Hartmann, Deckow and Kutch', 'Kenya');
insert into companies (nombre, nacionalidad) values ('Dach Inc', 'Canada');
insert into companies (nombre, nacionalidad) values ('Gislason-Wolff', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Dibbert, Bauch and Mosciski', 'Ghana');
insert into companies (nombre, nacionalidad) values ('Padberg, Schowalter and Tillman', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Lockman Group', 'Argentina');
insert into companies (nombre, nacionalidad) values ('O''Connell, Feeney and Hartmann', 'China');
insert into companies (nombre, nacionalidad) values ('Borer-Bernier', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Lueilwitz, Homenick and Homenick', 'Croatia');
insert into companies (nombre, nacionalidad) values ('Padberg-Torphy', 'United States');
insert into companies (nombre, nacionalidad) values ('Friesen-Collier', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Larson and Sons', 'Poland');
insert into companies (nombre, nacionalidad) values ('O''Reilly, Kertzmann and Halvorson', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Jakubowski, Frami and Auer', 'Canada');
insert into companies (nombre, nacionalidad) values ('Muller-Schneider', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Rippin Inc', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Daugherty-Goyette', 'Guinea');
insert into companies (nombre, nacionalidad) values ('Thiel-Dibbert', 'United States');
insert into companies (nombre, nacionalidad) values ('Gleichner-Kassulke', 'China');
insert into companies (nombre, nacionalidad) values ('Kuhn Group', 'Austria');
insert into companies (nombre, nacionalidad) values ('Herzog, Ledner and Ratke', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Auer-McLaughlin', 'China');
insert into companies (nombre, nacionalidad) values ('Schmidt Group', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Stracke, Larkin and Hamill', 'China');
insert into companies (nombre, nacionalidad) values ('Wisozk-Maggio', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Ankunding and Sons', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Aufderhar, Thiel and Spinka', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Volkman, Lindgren and Konopelski', 'Canada');
insert into companies (nombre, nacionalidad) values ('Weber-Rowe', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Wolff and Sons', 'Finland');
insert into companies (nombre, nacionalidad) values ('Beer LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Ernser and Sons', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Morissette-Leffler', 'China');
insert into companies (nombre, nacionalidad) values ('MacGyver and Sons', 'Poland');
insert into companies (nombre, nacionalidad) values ('Stehr-Bruen', 'Macedonia');
insert into companies (nombre, nacionalidad) values ('Kerluke and Sons', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Kshlerin, O''Connell and Kunze', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Lakin-Fay', 'Tunisia');
insert into companies (nombre, nacionalidad) values ('Zulauf, Nader and Dibbert', 'Greece');
insert into companies (nombre, nacionalidad) values ('Greenfelder, Paucek and Murazik', 'Afghanistan');
insert into companies (nombre, nacionalidad) values ('Collins-Emard', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Gottlieb-Erdman', 'China');
insert into companies (nombre, nacionalidad) values ('Kuphal, Dare and Heidenreich', 'Sierra Leone');
insert into companies (nombre, nacionalidad) values ('Fadel Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Auer Group', 'Russia');
insert into companies (nombre, nacionalidad) values ('Goldner, Beahan and Koch', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Purdy and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Toy, Raynor and Cassin', 'France');
insert into companies (nombre, nacionalidad) values ('Kerluke Inc', 'Russia');
insert into companies (nombre, nacionalidad) values ('Halvorson-Gorczany', 'Canada');
insert into companies (nombre, nacionalidad) values ('Lind Group', 'China');
insert into companies (nombre, nacionalidad) values ('Murazik Group', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Block-Fisher', 'Mongolia');
insert into companies (nombre, nacionalidad) values ('Metz LLC', 'France');
insert into companies (nombre, nacionalidad) values ('Larkin, Stanton and Rolfson', 'China');
insert into companies (nombre, nacionalidad) values ('Funk and Sons', 'Serbia');
insert into companies (nombre, nacionalidad) values ('Veum-Macejkovic', 'Nauru');
insert into companies (nombre, nacionalidad) values ('Gibson and Sons', 'Jamaica');
insert into companies (nombre, nacionalidad) values ('Rosenbaum-Jacobs', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Torp, Rippin and Roberts', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Halvorson, Casper and Terry', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Luettgen-Moen', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Schiller, Dibbert and Crist', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Gottlieb, Padberg and Feil', 'China');
insert into companies (nombre, nacionalidad) values ('Stokes Group', 'Poland');
insert into companies (nombre, nacionalidad) values ('Frami Group', 'China');
insert into companies (nombre, nacionalidad) values ('Jakubowski Inc', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Bins, Tromp and Skiles', 'Canada');
insert into companies (nombre, nacionalidad) values ('Price-Carter', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Koelpin Group', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Hintz Inc', 'Peru');
insert into companies (nombre, nacionalidad) values ('Weissnat, Schulist and Weber', 'Russia');
insert into companies (nombre, nacionalidad) values ('Gutkowski-Volkman', 'Ecuador');
insert into companies (nombre, nacionalidad) values ('Rohan Inc', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Green-Hagenes', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Schiller, Kirlin and Kuhn', 'China');
insert into companies (nombre, nacionalidad) values ('Bogisich-Greenfelder', 'China');
insert into companies (nombre, nacionalidad) values ('Gerhold, Balistreri and Wyman', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Okuneva, Haag and Tremblay', 'China');
insert into companies (nombre, nacionalidad) values ('Langosh Inc', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Bailey, Parisian and Aufderhar', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Ledner-Johnson', 'Canada');
insert into companies (nombre, nacionalidad) values ('Shanahan, Luettgen and Leannon', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Larson-Collins', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Cormier-Kunde', 'China');
insert into companies (nombre, nacionalidad) values ('Mosciski, Larkin and Raynor', 'Greece');
insert into companies (nombre, nacionalidad) values ('Jakubowski LLC', 'Poland');
insert into companies (nombre, nacionalidad) values ('Wolf, Brakus and Ryan', 'China');
insert into companies (nombre, nacionalidad) values ('Schulist Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Streich, Quitzon and Rolfson', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Skiles, Muller and Beier', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Hoeger, Nolan and Oberbrunner', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Bins-Walter', 'Cape Verde');
insert into companies (nombre, nacionalidad) values ('Wuckert-Reichert', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Kassulke, Raynor and Stiedemann', 'Russia');
insert into companies (nombre, nacionalidad) values ('Rohan Group', 'China');
insert into companies (nombre, nacionalidad) values ('Dietrich-Dooley', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Simonis-Hoppe', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Heidenreich Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Beatty LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Hessel-Heathcote', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Rath and Sons', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Weber-Prosacco', 'Canada');
insert into companies (nombre, nacionalidad) values ('Gottlieb and Sons', 'Finland');
insert into companies (nombre, nacionalidad) values ('Cremin LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Gleason, Renner and Ernser', 'China');
insert into companies (nombre, nacionalidad) values ('Williamson Group', 'France');
insert into companies (nombre, nacionalidad) values ('Turcotte Group', 'China');
insert into companies (nombre, nacionalidad) values ('Tromp Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Weimann-Raynor', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Walter-Windler', 'China');
insert into companies (nombre, nacionalidad) values ('Runte-Lindgren', 'South Africa');
insert into companies (nombre, nacionalidad) values ('Fadel Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Padberg Group', 'China');
insert into companies (nombre, nacionalidad) values ('Osinski, Muller and Feeney', 'China');
insert into companies (nombre, nacionalidad) values ('Kutch LLC', 'Ghana');
insert into companies (nombre, nacionalidad) values ('Bechtelar-Jakubowski', 'China');
insert into companies (nombre, nacionalidad) values ('Harvey, Kuphal and Hansen', 'Bosnia and Herzegovina');
insert into companies (nombre, nacionalidad) values ('Walter LLC', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Reinger, Ruecker and Hammes', 'Albania');
insert into companies (nombre, nacionalidad) values ('Considine-Okuneva', 'China');
insert into companies (nombre, nacionalidad) values ('Lueilwitz, Bahringer and Hane', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Mraz, Stark and Mohr', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Altenwerth-Crooks', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('O''Keefe Group', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Dickens, Schowalter and Bogisich', 'China');
insert into companies (nombre, nacionalidad) values ('Reilly-Hickle', 'Poland');
insert into companies (nombre, nacionalidad) values ('Murphy, Bayer and Wuckert', 'Russia');
insert into companies (nombre, nacionalidad) values ('Yundt Inc', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Collier Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Herman, Hodkiewicz and Smitham', 'Japan');
insert into companies (nombre, nacionalidad) values ('Brown and Sons', 'Japan');
insert into companies (nombre, nacionalidad) values ('Abbott Group', 'Canada');
insert into companies (nombre, nacionalidad) values ('Pollich LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Mitchell-Fahey', 'Lesotho');
insert into companies (nombre, nacionalidad) values ('Rempel LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Deckow-Luettgen', 'Yemen');
insert into companies (nombre, nacionalidad) values ('Hauck, Mante and Mohr', 'China');
insert into companies (nombre, nacionalidad) values ('Collins-Beier', 'Haiti');
insert into companies (nombre, nacionalidad) values ('Corkery-Conn', 'Zimbabwe');
insert into companies (nombre, nacionalidad) values ('VonRueden, Blanda and Hodkiewicz', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Denesik and Sons', 'France');
insert into companies (nombre, nacionalidad) values ('Runte, Thompson and Cruickshank', 'Russia');
insert into companies (nombre, nacionalidad) values ('Bruen, Schaefer and Haag', 'Honduras');
insert into companies (nombre, nacionalidad) values ('Schmitt-Simonis', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Botsford-Rath', 'China');
insert into companies (nombre, nacionalidad) values ('Zboncak and Sons', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Beahan and Sons', 'Russia');
insert into companies (nombre, nacionalidad) values ('Sawayn-King', 'Mauritius');
insert into companies (nombre, nacionalidad) values ('Bins Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Langosh, Mohr and Volkman', 'Niger');
insert into companies (nombre, nacionalidad) values ('Smith-Heaney', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Reinger-Hand', 'Poland');
insert into companies (nombre, nacionalidad) values ('Fritsch, Murphy and Nicolas', 'Peru');
insert into companies (nombre, nacionalidad) values ('Jast, Nienow and White', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('McCullough, Armstrong and Hodkiewicz', 'China');
insert into companies (nombre, nacionalidad) values ('Stehr-Abshire', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Feil Inc', 'Croatia');
insert into companies (nombre, nacionalidad) values ('Bogisich-Littel', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Kovacek-Boehm', 'Russia');
insert into companies (nombre, nacionalidad) values ('Lockman Group', 'France');
insert into companies (nombre, nacionalidad) values ('Luettgen, Prosacco and Schiller', 'Macedonia');
insert into companies (nombre, nacionalidad) values ('Langworth-Hartmann', 'Afghanistan');
insert into companies (nombre, nacionalidad) values ('Emmerich-Wolff', 'Somalia');
insert into companies (nombre, nacionalidad) values ('Schmitt LLC', 'Russia');
insert into companies (nombre, nacionalidad) values ('Effertz, Hills and Stanton', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Schiller Group', 'France');
insert into companies (nombre, nacionalidad) values ('Batz LLC', 'Guatemala');
insert into companies (nombre, nacionalidad) values ('Emard-Heidenreich', 'China');
insert into companies (nombre, nacionalidad) values ('Zboncak, Kuphal and Prohaska', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Olson LLC', 'Aruba');
insert into companies (nombre, nacionalidad) values ('Beahan, Jast and Graham', 'Argentina');
insert into companies (nombre, nacionalidad) values ('Weber-Johns', 'France');
insert into companies (nombre, nacionalidad) values ('Yost, Mohr and Nader', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Berge Group', 'Greece');
insert into companies (nombre, nacionalidad) values ('Flatley-Zemlak', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Metz-Torphy', 'South Sudan');
insert into companies (nombre, nacionalidad) values ('Fritsch, Osinski and Goodwin', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Hills-Kris', 'France');
insert into companies (nombre, nacionalidad) values ('Beatty LLC', 'Micronesia');
insert into companies (nombre, nacionalidad) values ('Osinski, Macejkovic and Hessel', 'Bolivia');
insert into companies (nombre, nacionalidad) values ('Smith-Wyman', 'Russia');
insert into companies (nombre, nacionalidad) values ('Welch-Torp', 'United States');
insert into companies (nombre, nacionalidad) values ('Mitchell, Robel and McKenzie', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Huel LLC', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Cummings Inc', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Mertz, Halvorson and Steuber', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Yundt, Pagac and Weissnat', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Bogisich, Walter and Klein', 'China');
insert into companies (nombre, nacionalidad) values ('Gottlieb, Bednar and Hagenes', 'Serbia');
insert into companies (nombre, nacionalidad) values ('Bayer Group', 'China');
insert into companies (nombre, nacionalidad) values ('Cassin-Grant', 'South Korea');
insert into companies (nombre, nacionalidad) values ('Haley LLC', 'Russia');
insert into companies (nombre, nacionalidad) values ('King, Jacobi and Schultz', 'France');
insert into companies (nombre, nacionalidad) values ('Balistreri, Schaden and Mueller', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Bruen, Bogisich and Ankunding', 'Armenia');
insert into companies (nombre, nacionalidad) values ('Wiegand Group', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Feil Group', 'China');
insert into companies (nombre, nacionalidad) values ('Streich-Harvey', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Bednar-Hilpert', 'China');
insert into companies (nombre, nacionalidad) values ('Jenkins-Rippin', 'Kazakhstan');
insert into companies (nombre, nacionalidad) values ('Gerlach, Rosenbaum and Pfannerstill', 'Malawi');
insert into companies (nombre, nacionalidad) values ('Walter-Stokes', 'Saint Kitts and Nevis');
insert into companies (nombre, nacionalidad) values ('Gutmann, Frami and Russel', 'China');
insert into companies (nombre, nacionalidad) values ('Quitzon, Grimes and Moore', 'Lebanon');
insert into companies (nombre, nacionalidad) values ('Daugherty, Treutel and Murphy', 'Russia');
insert into companies (nombre, nacionalidad) values ('Carter-Brown', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Littel, Stehr and Dickens', 'Zambia');
insert into companies (nombre, nacionalidad) values ('Macejkovic and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Ryan-Hettinger', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Prosacco Group', 'Japan');
insert into companies (nombre, nacionalidad) values ('Christiansen Inc', 'Morocco');
insert into companies (nombre, nacionalidad) values ('Hammes-Bergstrom', 'Poland');
insert into companies (nombre, nacionalidad) values ('Tremblay, Zboncak and Ledner', 'United States');
insert into companies (nombre, nacionalidad) values ('Kunze Group', 'Peru');
insert into companies (nombre, nacionalidad) values ('Roberts-McCullough', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Nienow-Streich', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Schumm-Ledner', 'China');
insert into companies (nombre, nacionalidad) values ('Deckow-Waters', 'Russia');
insert into companies (nombre, nacionalidad) values ('Doyle Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Bruen, Luettgen and Boyle', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Nienow-O''Hara', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Quitzon Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Bogan-Schultz', 'China');
insert into companies (nombre, nacionalidad) values ('Terry Inc', 'China');
insert into companies (nombre, nacionalidad) values ('King Inc', 'Russia');
insert into companies (nombre, nacionalidad) values ('Buckridge Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Bogisich-Stanton', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Rempel Inc', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Jast, Kilback and Jast', 'Mayotte');
insert into companies (nombre, nacionalidad) values ('Barton, Schaefer and Romaguera', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Schmidt, Cummings and Hagenes', 'Madagascar');
insert into companies (nombre, nacionalidad) values ('Thompson Inc', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Lowe-Legros', 'Bahrain');
insert into companies (nombre, nacionalidad) values ('Homenick Group', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Graham LLC', 'Iran');
insert into companies (nombre, nacionalidad) values ('MacGyver-Koelpin', 'Morocco');
insert into companies (nombre, nacionalidad) values ('Gislason-Hessel', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Champlin LLC', 'Dominican Republic');
insert into companies (nombre, nacionalidad) values ('Donnelly, Dicki and Hayes', 'Kenya');
insert into companies (nombre, nacionalidad) values ('Yundt-Kub', 'China');
insert into companies (nombre, nacionalidad) values ('Marvin, Kreiger and Balistreri', 'Russia');
insert into companies (nombre, nacionalidad) values ('Schumm, Schoen and O''Connell', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Goyette Group', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Kohler LLC', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Dietrich and Sons', 'Bulgaria');
insert into companies (nombre, nacionalidad) values ('Mann-O''Conner', 'Spain');
insert into companies (nombre, nacionalidad) values ('Stroman, Adams and Carter', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Reichert-Padberg', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Crist, Gulgowski and Armstrong', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Orn and Sons', 'Russia');
insert into companies (nombre, nacionalidad) values ('Weber, Tromp and Feeney', 'China');
insert into companies (nombre, nacionalidad) values ('Schumm Inc', 'Egypt');
insert into companies (nombre, nacionalidad) values ('Becker and Sons', 'Palestinian Territory');
insert into companies (nombre, nacionalidad) values ('Thompson-Sanford', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Murray-Lindgren', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Vandervort, Mueller and Dach', 'China');
insert into companies (nombre, nacionalidad) values ('Kohler and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Quitzon, Nicolas and Rau', 'Russia');
insert into companies (nombre, nacionalidad) values ('Sauer Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Wisoky-Watsica', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Stanton-Wuckert', 'Greece');
insert into companies (nombre, nacionalidad) values ('Dietrich, Grant and Dibbert', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Adams-Bosco', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Moen Inc', 'Germany');
insert into companies (nombre, nacionalidad) values ('Schuster Group', 'Russia');
insert into companies (nombre, nacionalidad) values ('Auer, Labadie and Boyer', 'China');
insert into companies (nombre, nacionalidad) values ('Volkman, Towne and Heidenreich', 'China');
insert into companies (nombre, nacionalidad) values ('Lowe-Bernhard', 'China');
insert into companies (nombre, nacionalidad) values ('Douglas and Sons', 'Kazakhstan');
insert into companies (nombre, nacionalidad) values ('Grant, Kuvalis and Terry', 'China');
insert into companies (nombre, nacionalidad) values ('Nicolas-Daniel', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Klein and Sons', 'Armenia');
insert into companies (nombre, nacionalidad) values ('Lockman, Pollich and Nader', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Blanda-Kiehn', 'Belarus');
insert into companies (nombre, nacionalidad) values ('Donnelly LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Feil-Carter', 'Peru');
insert into companies (nombre, nacionalidad) values ('Runte, Runte and Huel', 'Papua New Guinea');
insert into companies (nombre, nacionalidad) values ('Kihn, Jones and Hand', 'China');
insert into companies (nombre, nacionalidad) values ('Hauck, Mills and Nikolaus', 'China');
insert into companies (nombre, nacionalidad) values ('Heller-Strosin', 'Japan');
insert into companies (nombre, nacionalidad) values ('Reilly, Tromp and Yost', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Mayert, Marvin and Douglas', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('West Inc', 'Malaysia');
insert into companies (nombre, nacionalidad) values ('Effertz, Hagenes and Johnson', 'China');
insert into companies (nombre, nacionalidad) values ('Rolfson and Sons', 'Russia');
insert into companies (nombre, nacionalidad) values ('Streich, Kiehn and Stiedemann', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Ziemann, Boyer and Huels', 'Malaysia');
insert into companies (nombre, nacionalidad) values ('Hahn, Pacocha and Bailey', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Prohaska-Gibson', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Wiza LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Cronin Inc', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Kunze, Heller and Gleichner', 'Poland');
insert into companies (nombre, nacionalidad) values ('Mraz, Rogahn and Nader', 'France');
insert into companies (nombre, nacionalidad) values ('Toy Group', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Hills Inc', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Reichel-Leuschke', 'Ecuador');
insert into companies (nombre, nacionalidad) values ('Marvin, Keebler and Goodwin', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Ruecker-Rohan', 'Egypt');
insert into companies (nombre, nacionalidad) values ('Schultz-Morar', 'United Kingdom');
insert into companies (nombre, nacionalidad) values ('Becker-Swaniawski', 'Serbia');
insert into companies (nombre, nacionalidad) values ('Kemmer, Labadie and Hoppe', 'China');
insert into companies (nombre, nacionalidad) values ('Lehner-Cronin', 'Jordan');
insert into companies (nombre, nacionalidad) values ('Abernathy LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Corkery LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Wiegand, Simonis and Howe', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Denesik-Reynolds', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Simonis, Thompson and Ondricka', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Gislason, Goldner and Gleason', 'Macedonia');
insert into companies (nombre, nacionalidad) values ('Borer, Schmeler and Satterfield', 'Portugal');
insert into companies (nombre, nacionalidad) values ('O''Conner, Langworth and Jacobs', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Beier-DuBuque', 'China');
insert into companies (nombre, nacionalidad) values ('Wyman LLC', 'France');
insert into companies (nombre, nacionalidad) values ('Stark-Considine', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Cormier-Mills', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Fahey, Daniel and Collier', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Streich-Conroy', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Stiedemann-Hoeger', 'Malaysia');
insert into companies (nombre, nacionalidad) values ('Dooley, Satterfield and Welch', 'Japan');
insert into companies (nombre, nacionalidad) values ('Hammes, Goodwin and Larkin', 'Armenia');
insert into companies (nombre, nacionalidad) values ('Block, Schmitt and Klocko', 'China');
insert into companies (nombre, nacionalidad) values ('O''Reilly Inc', 'Poland');
insert into companies (nombre, nacionalidad) values ('Rutherford-Stehr', 'China');
insert into companies (nombre, nacionalidad) values ('Osinski-Ratke', 'Tunisia');
insert into companies (nombre, nacionalidad) values ('Gulgowski-Feest', 'Poland');
insert into companies (nombre, nacionalidad) values ('Yost Inc', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Howe-Franecki', 'Morocco');
insert into companies (nombre, nacionalidad) values ('Rempel, Littel and Huel', 'Namibia');
insert into companies (nombre, nacionalidad) values ('Heathcote, Will and Olson', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Kub-Lemke', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Harber Group', 'Ireland');
insert into companies (nombre, nacionalidad) values ('Grimes, Yundt and Hackett', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Krajcik, Weimann and Weissnat', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Larson LLC', 'Philippines');
insert into companies (nombre, nacionalidad) values ('West, Sawayn and Wolff', 'Germany');
insert into companies (nombre, nacionalidad) values ('Lebsack, Reinger and Nitzsche', 'United States');
insert into companies (nombre, nacionalidad) values ('Ortiz, Bednar and Hane', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Trantow, Predovic and Hyatt', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Nienow LLC', 'Russia');
insert into companies (nombre, nacionalidad) values ('Feeney Group', 'China');
insert into companies (nombre, nacionalidad) values ('Gutmann, Hayes and Pfeffer', 'China');
insert into companies (nombre, nacionalidad) values ('Spencer Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Crona LLC', 'Lebanon');
insert into companies (nombre, nacionalidad) values ('Hessel, Davis and Hickle', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Gusikowski, Parker and Bernhard', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Kulas-Turner', 'Macedonia');
insert into companies (nombre, nacionalidad) values ('Wintheiser-Gleason', 'Greece');
insert into companies (nombre, nacionalidad) values ('Leffler LLC', 'Peru');
insert into companies (nombre, nacionalidad) values ('Beer LLC', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Johns Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Jenkins Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Bins and Sons', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Rolfson Inc', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Smith-Pouros', 'Chile');
insert into companies (nombre, nacionalidad) values ('Beatty-Gusikowski', 'China');
insert into companies (nombre, nacionalidad) values ('Yundt-Feil', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Halvorson Group', 'China');
insert into companies (nombre, nacionalidad) values ('Kassulke-McGlynn', 'France');
insert into companies (nombre, nacionalidad) values ('Zieme Inc', 'United States');
insert into companies (nombre, nacionalidad) values ('Emmerich Group', 'China');
insert into companies (nombre, nacionalidad) values ('Graham, Ryan and Predovic', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Stehr, Hills and Hegmann', 'Uruguay');
insert into companies (nombre, nacionalidad) values ('Russel, Gusikowski and Mitchell', 'China');
insert into companies (nombre, nacionalidad) values ('Osinski and Sons', 'Oman');
insert into companies (nombre, nacionalidad) values ('Altenwerth, Shanahan and Kulas', 'Peru');
insert into companies (nombre, nacionalidad) values ('Brekke and Sons', 'Bosnia and Herzegovina');
insert into companies (nombre, nacionalidad) values ('Torp, Ward and Cronin', 'Kazakhstan');
insert into companies (nombre, nacionalidad) values ('Maggio-Bergnaum', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Donnelly Inc', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Powlowski LLC', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Yundt, Sauer and Schumm', 'Russia');
insert into companies (nombre, nacionalidad) values ('Hauck, Weimann and Langworth', 'Poland');
insert into companies (nombre, nacionalidad) values ('Bernier Group', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Keeling, O''Reilly and Stamm', 'Russia');
insert into companies (nombre, nacionalidad) values ('Hansen LLC', 'Poland');
insert into companies (nombre, nacionalidad) values ('Feeney, Rowe and Ratke', 'China');
insert into companies (nombre, nacionalidad) values ('O''Conner and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Deckow, Hahn and Carter', 'China');
insert into companies (nombre, nacionalidad) values ('Torp, Daniel and Boyer', 'Peru');
insert into companies (nombre, nacionalidad) values ('McLaughlin Group', 'Russia');
insert into companies (nombre, nacionalidad) values ('Brown, Langworth and Halvorson', 'United States');
insert into companies (nombre, nacionalidad) values ('Hettinger-Zieme', 'China');
insert into companies (nombre, nacionalidad) values ('Kessler-Schuster', 'Kenya');
insert into companies (nombre, nacionalidad) values ('Casper, Kozey and Goyette', 'Poland');
insert into companies (nombre, nacionalidad) values ('Greenfelder Inc', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Gerlach Inc', 'Poland');
insert into companies (nombre, nacionalidad) values ('Wisozk, VonRueden and Conroy', 'China');
insert into companies (nombre, nacionalidad) values ('Harvey, Denesik and Sauer', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Stehr-Bahringer', 'Russia');
insert into companies (nombre, nacionalidad) values ('Sipes, Corwin and Okuneva', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Thompson Inc', 'Russia');
insert into companies (nombre, nacionalidad) values ('Balistreri and Sons', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Harber Inc', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Weissnat-Jacobs', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Hansen-McLaughlin', 'United States');
insert into companies (nombre, nacionalidad) values ('Price Group', 'Russia');
insert into companies (nombre, nacionalidad) values ('Cruickshank, Tillman and Grant', 'Russia');
insert into companies (nombre, nacionalidad) values ('Gibson and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Sipes Group', 'United States');
insert into companies (nombre, nacionalidad) values ('Donnelly-Rice', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Davis, Gleichner and Koch', 'China');
insert into companies (nombre, nacionalidad) values ('Heidenreich, Heller and Blanda', 'Poland');
insert into companies (nombre, nacionalidad) values ('Predovic-Gulgowski', 'Singapore');
insert into companies (nombre, nacionalidad) values ('Lakin, Rohan and Mertz', 'Russia');
insert into companies (nombre, nacionalidad) values ('Mosciski Group', 'Japan');
insert into companies (nombre, nacionalidad) values ('Haag, Purdy and Hartmann', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Mills Inc', 'Poland');
insert into companies (nombre, nacionalidad) values ('Pouros LLC', 'Cuba');
insert into companies (nombre, nacionalidad) values ('Koch, Mann and Medhurst', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Walsh, Wehner and Marks', 'United States');
insert into companies (nombre, nacionalidad) values ('Lang-Conn', 'France');
insert into companies (nombre, nacionalidad) values ('Lynch LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Hilpert Group', 'France');
insert into companies (nombre, nacionalidad) values ('Kozey, Stroman and Stanton', 'France');
insert into companies (nombre, nacionalidad) values ('White, Terry and Tremblay', 'China');
insert into companies (nombre, nacionalidad) values ('Bogan, Keebler and Goldner', 'Bosnia and Herzegovina');
insert into companies (nombre, nacionalidad) values ('Waelchi, Harris and Carter', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Bailey, Bechtelar and Conroy', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Leannon, Cummings and Hodkiewicz', 'Mongolia');
insert into companies (nombre, nacionalidad) values ('Keeling, Nader and Runolfsson', 'China');
insert into companies (nombre, nacionalidad) values ('Kozey-Jenkins', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Yost, Breitenberg and Bergnaum', 'Albania');
insert into companies (nombre, nacionalidad) values ('Hudson Inc', 'Poland');
insert into companies (nombre, nacionalidad) values ('Strosin, Rosenbaum and Hirthe', 'Gambia');
insert into companies (nombre, nacionalidad) values ('Cartwright and Sons', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Hoeger LLC', 'Brazil');
insert into companies (nombre, nacionalidad) values ('West-Hane', 'Canada');
insert into companies (nombre, nacionalidad) values ('Gerlach-Prosacco', 'Tunisia');
insert into companies (nombre, nacionalidad) values ('Ondricka Group', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Hickle, Larkin and Rogahn', 'Russia');
insert into companies (nombre, nacionalidad) values ('Klocko Inc', 'Norway');
insert into companies (nombre, nacionalidad) values ('Senger, Wyman and Ryan', 'China');
insert into companies (nombre, nacionalidad) values ('White-Bechtelar', 'China');
insert into companies (nombre, nacionalidad) values ('Cassin-Morissette', 'Honduras');
insert into companies (nombre, nacionalidad) values ('Connelly and Sons', 'France');
insert into companies (nombre, nacionalidad) values ('Raynor-Kerluke', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Reichel and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Barton Group', 'China');
insert into companies (nombre, nacionalidad) values ('Collins-Lehner', 'China');
insert into companies (nombre, nacionalidad) values ('Beatty-Sawayn', 'China');
insert into companies (nombre, nacionalidad) values ('Erdman, Toy and Kreiger', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Simonis Inc', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Beier-Stroman', 'American Samoa');
insert into companies (nombre, nacionalidad) values ('Leuschke-Halvorson', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Bernhard Group', 'Argentina');
insert into companies (nombre, nacionalidad) values ('Willms, McGlynn and Kunze', 'Ecuador');
insert into companies (nombre, nacionalidad) values ('Kirlin-Beer', 'Russia');
insert into companies (nombre, nacionalidad) values ('Hackett-Bins', 'France');
insert into companies (nombre, nacionalidad) values ('Haag-Ruecker', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Crona, Kohler and Adams', 'Syria');
insert into companies (nombre, nacionalidad) values ('Howe-Carroll', 'Cameroon');
insert into companies (nombre, nacionalidad) values ('Zieme and Sons', 'Bulgaria');
insert into companies (nombre, nacionalidad) values ('Bayer-Kirlin', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Ernser-Erdman', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Swaniawski, Hartmann and Thiel', 'China');
insert into companies (nombre, nacionalidad) values ('Boyle, Abshire and Hermann', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Osinski LLC', 'Russia');
insert into companies (nombre, nacionalidad) values ('Lang Group', 'Mongolia');
insert into companies (nombre, nacionalidad) values ('Wiza, Pfeffer and Kris', 'Cameroon');
insert into companies (nombre, nacionalidad) values ('Bartoletti, Blick and Yost', 'France');
insert into companies (nombre, nacionalidad) values ('Feeney-Kling', 'Russia');
insert into companies (nombre, nacionalidad) values ('Dickinson, Hane and Nitzsche', 'China');
insert into companies (nombre, nacionalidad) values ('Huels Group', 'Russia');
insert into companies (nombre, nacionalidad) values ('Bradtke-Schuster', 'China');
insert into companies (nombre, nacionalidad) values ('Kemmer-Morissette', 'China');
insert into companies (nombre, nacionalidad) values ('Schneider LLC', 'Azerbaijan');
insert into companies (nombre, nacionalidad) values ('Romaguera-Pollich', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Bernier, Schmeler and Weimann', 'Bulgaria');
insert into companies (nombre, nacionalidad) values ('Cummings-Runolfsson', 'Cyprus');
insert into companies (nombre, nacionalidad) values ('Becker, Jones and Kautzer', 'China');
insert into companies (nombre, nacionalidad) values ('Gulgowski LLC', 'Russia');
insert into companies (nombre, nacionalidad) values ('Johnson, Champlin and Turcotte', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Bashirian and Sons', 'Italy');
insert into companies (nombre, nacionalidad) values ('Hettinger-Keebler', 'Armenia');
insert into companies (nombre, nacionalidad) values ('Stark-Dietrich', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Kub-Willms', 'Ireland');
insert into companies (nombre, nacionalidad) values ('Connelly, Waelchi and Oberbrunner', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Bahringer and Sons', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Larkin-Jast', 'Pakistan');
insert into companies (nombre, nacionalidad) values ('Wyman-Okuneva', 'Panama');
insert into companies (nombre, nacionalidad) values ('Luettgen Inc', 'Myanmar');
insert into companies (nombre, nacionalidad) values ('McClure Inc', 'France');
insert into companies (nombre, nacionalidad) values ('Funk, Kohler and Mosciski', 'United States');
insert into companies (nombre, nacionalidad) values ('Buckridge-Pollich', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Abbott LLC', 'Belarus');
insert into companies (nombre, nacionalidad) values ('Morissette LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Trantow-Larkin', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Douglas-Schiller', 'Morocco');
insert into companies (nombre, nacionalidad) values ('Hyatt Group', 'Luxembourg');
insert into companies (nombre, nacionalidad) values ('Will-Hand', 'China');
insert into companies (nombre, nacionalidad) values ('Pouros LLC', 'Uruguay');
insert into companies (nombre, nacionalidad) values ('Wehner, Gerlach and Abbott', 'China');
insert into companies (nombre, nacionalidad) values ('Kilback-Bode', 'Bulgaria');
insert into companies (nombre, nacionalidad) values ('Pouros Inc', 'Peru');
insert into companies (nombre, nacionalidad) values ('DuBuque LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Olson, Price and Lehner', 'Croatia');
insert into companies (nombre, nacionalidad) values ('Schultz-Keebler', 'Russia');
insert into companies (nombre, nacionalidad) values ('Hermann-Stoltenberg', 'China');
insert into companies (nombre, nacionalidad) values ('Morar-Cole', 'Argentina');
insert into companies (nombre, nacionalidad) values ('Rath-Feeney', 'France');
insert into companies (nombre, nacionalidad) values ('Fritsch, Mueller and Kris', 'Netherlands');
insert into companies (nombre, nacionalidad) values ('Deckow-O''Keefe', 'France');
insert into companies (nombre, nacionalidad) values ('Corwin, Berge and Stoltenberg', 'Iceland');
insert into companies (nombre, nacionalidad) values ('Mraz, Ryan and Windler', 'Senegal');
insert into companies (nombre, nacionalidad) values ('Sipes Group', 'Chad');
insert into companies (nombre, nacionalidad) values ('Murray Group', 'Poland');
insert into companies (nombre, nacionalidad) values ('King-Schinner', 'Ecuador');
insert into companies (nombre, nacionalidad) values ('Pagac-O''Kon', 'North Korea');
insert into companies (nombre, nacionalidad) values ('Orn LLC', 'Sweden');
insert into companies (nombre, nacionalidad) values ('D''Amore LLC', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Borer-Mante', 'China');
insert into companies (nombre, nacionalidad) values ('Rempel, Cummerata and Sanford', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Crona, Reilly and Weissnat', 'China');
insert into companies (nombre, nacionalidad) values ('Doyle LLC', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Gorczany Inc', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Nolan Group', 'Maldives');
insert into companies (nombre, nacionalidad) values ('Hahn Inc', 'Russia');
insert into companies (nombre, nacionalidad) values ('Gutkowski-Murazik', 'United Kingdom');
insert into companies (nombre, nacionalidad) values ('Gusikowski, Champlin and Funk', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Kohler-Kunze', 'United States');
insert into companies (nombre, nacionalidad) values ('Bogisich, Wiegand and Bauch', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Klein, Gislason and Sporer', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Zemlak Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Baumbach, Harvey and Ratke', 'Poland');
insert into companies (nombre, nacionalidad) values ('Reinger, Volkman and Rau', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Zboncak-Schultz', 'China');
insert into companies (nombre, nacionalidad) values ('Wolf LLC', 'Panama');
insert into companies (nombre, nacionalidad) values ('Metz Inc', 'Yemen');
insert into companies (nombre, nacionalidad) values ('Schultz, Price and Breitenberg', 'China');
insert into companies (nombre, nacionalidad) values ('Maggio, Reynolds and Witting', 'Greece');
insert into companies (nombre, nacionalidad) values ('Sawayn, Howe and Olson', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Cassin, Langworth and Funk', 'Albania');
insert into companies (nombre, nacionalidad) values ('Rogahn, Hermiston and Donnelly', 'China');
insert into companies (nombre, nacionalidad) values ('Johnson-Hansen', 'China');
insert into companies (nombre, nacionalidad) values ('Hodkiewicz-Littel', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Sawayn Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Walsh and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Quitzon, Metz and Zieme', 'Kazakhstan');
insert into companies (nombre, nacionalidad) values ('Wuckert and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Larkin-Price', 'China');
insert into companies (nombre, nacionalidad) values ('Stark, Abshire and Reynolds', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Gerlach Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Wuckert Group', 'Chile');
insert into companies (nombre, nacionalidad) values ('Ratke and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Ziemann-Emmerich', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('McKenzie and Sons', 'Canada');
insert into companies (nombre, nacionalidad) values ('Schuppe, Hahn and Blick', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Kutch-Braun', 'Argentina');
insert into companies (nombre, nacionalidad) values ('Sporer, Kuhn and Ryan', 'Luxembourg');
insert into companies (nombre, nacionalidad) values ('Gerhold LLC', 'South Africa');
insert into companies (nombre, nacionalidad) values ('Purdy-Larkin', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Mills-Parker', 'Russia');
insert into companies (nombre, nacionalidad) values ('Hammes-Lang', 'China');
insert into companies (nombre, nacionalidad) values ('Leannon, Green and Lindgren', 'Argentina');
insert into companies (nombre, nacionalidad) values ('Ledner Group', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Osinski and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Blanda-Waters', 'Finland');
insert into companies (nombre, nacionalidad) values ('Gerhold-DuBuque', 'China');
insert into companies (nombre, nacionalidad) values ('Moore LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Zieme, Friesen and Collins', 'Uzbekistan');
insert into companies (nombre, nacionalidad) values ('Romaguera-Parisian', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Yost-Rohan', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Lakin Inc', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Ortiz-Schmitt', 'China');
insert into companies (nombre, nacionalidad) values ('Satterfield-VonRueden', 'Belgium');
insert into companies (nombre, nacionalidad) values ('Kassulke Inc', 'Malaysia');
insert into companies (nombre, nacionalidad) values ('Steuber-Jakubowski', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Witting and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Luettgen Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Lang-Weber', 'China');
insert into companies (nombre, nacionalidad) values ('Ullrich, Halvorson and Leffler', 'China');
insert into companies (nombre, nacionalidad) values ('Hessel, Krajcik and Bahringer', 'Canada');
insert into companies (nombre, nacionalidad) values ('Hilll-Heller', 'Saudi Arabia');
insert into companies (nombre, nacionalidad) values ('Barton and Sons', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Hansen, Fay and Becker', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Prosacco, Franecki and Skiles', 'China');
insert into companies (nombre, nacionalidad) values ('Huels-Crona', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Heaney-Kilback', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Bradtke, Reilly and Grady', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Grimes-Hintz', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Wyman Group', 'Macedonia');
insert into companies (nombre, nacionalidad) values ('Gaylord-Friesen', 'Russia');
insert into companies (nombre, nacionalidad) values ('Abshire Inc', 'Peru');
insert into companies (nombre, nacionalidad) values ('Ryan, Cremin and Konopelski', 'Cape Verde');
insert into companies (nombre, nacionalidad) values ('Spencer-Schuppe', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Prosacco, Willms and Hauck', 'Finland');
insert into companies (nombre, nacionalidad) values ('Grimes-Hand', 'China');
insert into companies (nombre, nacionalidad) values ('Stamm Inc', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Dare, O''Reilly and Carter', 'Nicaragua');
insert into companies (nombre, nacionalidad) values ('Schoen LLC', 'Armenia');
insert into companies (nombre, nacionalidad) values ('Waelchi Inc', 'United States');
insert into companies (nombre, nacionalidad) values ('Leannon Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Beer-Dickens', 'Argentina');
insert into companies (nombre, nacionalidad) values ('Russel Group', 'South Africa');
insert into companies (nombre, nacionalidad) values ('Toy, Mayert and Kessler', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Heathcote, Glover and Morissette', 'French Polynesia');
insert into companies (nombre, nacionalidad) values ('Kihn-Dickens', 'Chile');
insert into companies (nombre, nacionalidad) values ('Heaney Inc', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Ward, Koepp and Feil', 'Venezuela');
insert into companies (nombre, nacionalidad) values ('Luettgen LLC', 'Peru');
insert into companies (nombre, nacionalidad) values ('Morar and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Borer, Rosenbaum and Kling', 'Greece');
insert into companies (nombre, nacionalidad) values ('Cruickshank Inc', 'Tanzania');
insert into companies (nombre, nacionalidad) values ('Goodwin and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Gleichner-Metz', 'Poland');
insert into companies (nombre, nacionalidad) values ('Witting-Larson', 'China');
insert into companies (nombre, nacionalidad) values ('Kiehn Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Nolan, Sawayn and Considine', 'Peru');
insert into companies (nombre, nacionalidad) values ('Corwin-Pouros', 'China');
insert into companies (nombre, nacionalidad) values ('Schinner, Kris and Marks', 'Syria');
insert into companies (nombre, nacionalidad) values ('Zemlak-Erdman', 'South Africa');
insert into companies (nombre, nacionalidad) values ('Leffler-Pouros', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Hilll LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Schultz, Langosh and Grimes', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Johns Group', 'Belgium');
insert into companies (nombre, nacionalidad) values ('Schneider Inc', 'China');
insert into companies (nombre, nacionalidad) values ('McKenzie Group', 'Peru');
insert into companies (nombre, nacionalidad) values ('Schaefer and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('O''Hara Inc', 'France');
insert into companies (nombre, nacionalidad) values ('Balistreri-Cummerata', 'Poland');
insert into companies (nombre, nacionalidad) values ('Reynolds-Deckow', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Jakubowski and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Huel-Casper', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('O''Keefe Group', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Rath Group', 'South Korea');
insert into companies (nombre, nacionalidad) values ('Mohr Group', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Keeling-Treutel', 'Israel');
insert into companies (nombre, nacionalidad) values ('Denesik Group', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Connelly, Leffler and Dooley', 'Greece');
insert into companies (nombre, nacionalidad) values ('Legros, Weissnat and Macejkovic', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Corkery LLC', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Feil Inc', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Hodkiewicz-Schinner', 'China');
insert into companies (nombre, nacionalidad) values ('Nikolaus, Farrell and Hilpert', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Blanda Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Hermann, Medhurst and Skiles', 'China');
insert into companies (nombre, nacionalidad) values ('Bauch, Will and Keebler', 'France');
insert into companies (nombre, nacionalidad) values ('McGlynn Inc', 'China');
insert into companies (nombre, nacionalidad) values ('O''Hara-Reichel', 'China');
insert into companies (nombre, nacionalidad) values ('Mitchell, Jenkins and Quigley', 'South Africa');
insert into companies (nombre, nacionalidad) values ('Will Inc', 'France');
insert into companies (nombre, nacionalidad) values ('Schmidt Inc', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Waelchi Group', 'France');
insert into companies (nombre, nacionalidad) values ('Gleason and Sons', 'Belarus');
insert into companies (nombre, nacionalidad) values ('Howe, Lind and Steuber', 'China');
insert into companies (nombre, nacionalidad) values ('Gerlach, Roberts and Gutkowski', 'Croatia');
insert into companies (nombre, nacionalidad) values ('Lesch-Sporer', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Lynch-Kirlin', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Funk, Kassulke and Lang', 'Russia');
insert into companies (nombre, nacionalidad) values ('Donnelly LLC', 'Serbia');
insert into companies (nombre, nacionalidad) values ('Casper, Corkery and Morar', 'France');
insert into companies (nombre, nacionalidad) values ('Labadie, Hudson and Bayer', 'Germany');
insert into companies (nombre, nacionalidad) values ('Hegmann-Rice', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Thiel-Cormier', 'Netherlands');
insert into companies (nombre, nacionalidad) values ('Funk LLC', 'Ukraine');
insert into companies (nombre, nacionalidad) values ('Luettgen-Beier', 'China');
insert into companies (nombre, nacionalidad) values ('Daugherty, Bauch and Franecki', 'Philippines');
insert into companies (nombre, nacionalidad) values ('DuBuque, Kassulke and Koss', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Nienow, Collins and Block', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Baumbach Group', 'China');
insert into companies (nombre, nacionalidad) values ('Huel, Weimann and Haley', 'Estonia');
insert into companies (nombre, nacionalidad) values ('Koch, Moen and Quitzon', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Pagac-Gottlieb', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Hoeger-Langworth', 'Kenya');
insert into companies (nombre, nacionalidad) values ('Windler-Abbott', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Howell, Predovic and Wiza', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Goodwin-Barrows', 'Poland');
insert into companies (nombre, nacionalidad) values ('Koch LLC', 'Zimbabwe');
insert into companies (nombre, nacionalidad) values ('Schuppe Inc', 'Zimbabwe');
insert into companies (nombre, nacionalidad) values ('Jast, Murphy and Satterfield', 'China');
insert into companies (nombre, nacionalidad) values ('Johnson Group', 'Yemen');
insert into companies (nombre, nacionalidad) values ('Johns and Sons', 'Morocco');
insert into companies (nombre, nacionalidad) values ('Fadel, Gislason and Kling', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Buckridge-Abbott', 'Japan');
insert into companies (nombre, nacionalidad) values ('Pacocha-Quitzon', 'Brazil');
insert into companies (nombre, nacionalidad) values ('O''Keefe-Gleason', 'Poland');
insert into companies (nombre, nacionalidad) values ('Rogahn-Cronin', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('King Group', 'Russia');
insert into companies (nombre, nacionalidad) values ('Barton, Kunde and O''Kon', 'Georgia');
insert into companies (nombre, nacionalidad) values ('Beier Group', 'China');
insert into companies (nombre, nacionalidad) values ('Brakus, Olson and Yost', 'Lithuania');
insert into companies (nombre, nacionalidad) values ('Kling-Grady', 'Brazil');
insert into companies (nombre, nacionalidad) values ('McLaughlin, Marks and Boyle', 'China');
insert into companies (nombre, nacionalidad) values ('Streich LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Ward, Streich and Ratke', 'China');
insert into companies (nombre, nacionalidad) values ('Champlin, Lang and Murray', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Brekke LLC', 'Belarus');
insert into companies (nombre, nacionalidad) values ('Leuschke, Swift and Bednar', 'France');
insert into companies (nombre, nacionalidad) values ('Doyle Inc', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Becker Inc', 'Paraguay');
insert into companies (nombre, nacionalidad) values ('Thompson, Russel and Schulist', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Kiehn, Hermiston and Waelchi', 'Moldova');
insert into companies (nombre, nacionalidad) values ('Watsica and Sons', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Torphy, Hagenes and Rodriguez', 'China');
insert into companies (nombre, nacionalidad) values ('Littel LLC', 'Chile');
insert into companies (nombre, nacionalidad) values ('Douglas, Waelchi and Stehr', 'Ecuador');
insert into companies (nombre, nacionalidad) values ('Kemmer-Cummerata', 'Micronesia');
insert into companies (nombre, nacionalidad) values ('McClure LLC', 'China');
insert into companies (nombre, nacionalidad) values ('Cummerata, Miller and Krajcik', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Ruecker-Labadie', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Cruickshank-Rippin', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Botsford and Sons', 'United States');
insert into companies (nombre, nacionalidad) values ('Keeling-Crona', 'Mauritius');
insert into companies (nombre, nacionalidad) values ('Mueller and Sons', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Kovacek, Breitenberg and Schiller', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Hettinger LLC', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Cormier Inc', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Collier LLC', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Metz-Koss', 'Mongolia');
insert into companies (nombre, nacionalidad) values ('Mitchell Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Stracke, Watsica and Ebert', 'Morocco');
insert into companies (nombre, nacionalidad) values ('Schamberger, Bradtke and Johnson', 'Russia');
insert into companies (nombre, nacionalidad) values ('Prosacco, Weissnat and Renner', 'France');
insert into companies (nombre, nacionalidad) values ('Simonis-Ryan', 'Portugal');
insert into companies (nombre, nacionalidad) values ('King LLC', 'Tanzania');
insert into companies (nombre, nacionalidad) values ('Corkery Inc', 'Russia');
insert into companies (nombre, nacionalidad) values ('Wilderman-Altenwerth', 'China');
insert into companies (nombre, nacionalidad) values ('Halvorson Group', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Fadel, Beer and Wuckert', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('MacGyver LLC', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Reinger-Torp', 'Finland');
insert into companies (nombre, nacionalidad) values ('Williamson and Sons', 'Sierra Leone');
insert into companies (nombre, nacionalidad) values ('Funk-McClure', 'France');
insert into companies (nombre, nacionalidad) values ('Walter, Jaskolski and Gusikowski', 'China');
insert into companies (nombre, nacionalidad) values ('Kassulke LLC', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Swift, Wunsch and Ruecker', 'Ivory Coast');
insert into companies (nombre, nacionalidad) values ('Towne-Bartoletti', 'Peru');
insert into companies (nombre, nacionalidad) values ('Barton-MacGyver', 'China');
insert into companies (nombre, nacionalidad) values ('Konopelski and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Abernathy, Baumbach and Legros', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Kovacek, Pacocha and Mueller', 'China');
insert into companies (nombre, nacionalidad) values ('Blanda, Yundt and Parisian', 'Botswana');
insert into companies (nombre, nacionalidad) values ('Walker, Braun and Will', 'Czech Republic');
insert into companies (nombre, nacionalidad) values ('Ebert-Kuhic', 'Afghanistan');
insert into companies (nombre, nacionalidad) values ('Wilkinson-Walsh', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Rempel, Jenkins and Tremblay', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Tremblay-Wiegand', 'Peru');
insert into companies (nombre, nacionalidad) values ('Hansen Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Kuhlman, Langosh and Zieme', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Johnson Inc', 'China');
insert into companies (nombre, nacionalidad) values ('Marvin-Corkery', 'China');
insert into companies (nombre, nacionalidad) values ('Paucek LLC', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Haley and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Wunsch Inc', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Goldner and Sons', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Marquardt and Sons', 'France');
insert into companies (nombre, nacionalidad) values ('Corwin-Bosco', 'Canada');
insert into companies (nombre, nacionalidad) values ('Feeney Group', 'United States');
insert into companies (nombre, nacionalidad) values ('Schmeler, Luettgen and Mertz', 'Iran');
insert into companies (nombre, nacionalidad) values ('Trantow-Yundt', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Botsford-Lindgren', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Mann, Swaniawski and Marquardt', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Larkin, Kerluke and Braun', 'Russia');
insert into companies (nombre, nacionalidad) values ('Pollich, Mann and Mante', 'Pakistan');
insert into companies (nombre, nacionalidad) values ('Pfeffer, Ratke and Fisher', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Rath and Sons', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Hansen Inc', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Morar Inc', 'Japan');
insert into companies (nombre, nacionalidad) values ('Lindgren-Becker', 'Dominican Republic');
insert into companies (nombre, nacionalidad) values ('Renner-Mertz', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Zieme, Johnston and Greenfelder', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Denesik-Becker', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Nienow Group', 'Kazakhstan');
insert into companies (nombre, nacionalidad) values ('Ullrich Group', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Effertz-Hackett', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Crona, Rath and Pfeffer', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Brown, Satterfield and DuBuque', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Koss-Gaylord', 'China');
insert into companies (nombre, nacionalidad) values ('White-Nikolaus', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Rohan-Stiedemann', 'Russia');
insert into companies (nombre, nacionalidad) values ('Bartell-Steuber', 'Honduras');
insert into companies (nombre, nacionalidad) values ('Cummerata, Lynch and Bahringer', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Mosciski, Stehr and Doyle', 'China');
insert into companies (nombre, nacionalidad) values ('Bernier-Cartwright', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Kuhic Group', 'Canada');
insert into companies (nombre, nacionalidad) values ('Hoeger, Wolff and Bins', 'Tajikistan');
insert into companies (nombre, nacionalidad) values ('Muller LLC', 'Pakistan');
insert into companies (nombre, nacionalidad) values ('Boehm, Bosco and Lynch', 'Mongolia');
insert into companies (nombre, nacionalidad) values ('Gerhold-McCullough', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Volkman, Frami and Effertz', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Murazik Group', 'Argentina');
insert into companies (nombre, nacionalidad) values ('Lynch-Rice', 'China');
insert into companies (nombre, nacionalidad) values ('Crooks Group', 'China');
insert into companies (nombre, nacionalidad) values ('Gerlach-Rath', 'Greece');
insert into companies (nombre, nacionalidad) values ('Rath-Aufderhar', 'China');
insert into companies (nombre, nacionalidad) values ('Lindgren Group', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Volkman, Lockman and Wilkinson', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Moore-Bartell', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Emmerich-Schultz', 'Ethiopia');
insert into companies (nombre, nacionalidad) values ('Yundt and Sons', 'Iran');
insert into companies (nombre, nacionalidad) values ('Kassulke-Schaefer', 'United States');
insert into companies (nombre, nacionalidad) values ('Fahey, Luettgen and Jacobi', 'South Africa');
insert into companies (nombre, nacionalidad) values ('Stiedemann-Nitzsche', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Weissnat-Pfannerstill', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Konopelski, Feil and Rowe', 'Serbia');
insert into companies (nombre, nacionalidad) values ('Klocko and Sons', 'Cameroon');
insert into companies (nombre, nacionalidad) values ('Johnston-King', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Terry, Aufderhar and Walsh', 'Sweden');
insert into companies (nombre, nacionalidad) values ('Medhurst, Marvin and Sipes', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Casper-Hegmann', 'China');
insert into companies (nombre, nacionalidad) values ('Carter, Schumm and Lind', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Kub-Konopelski', 'Netherlands');
insert into companies (nombre, nacionalidad) values ('Zemlak-Runolfsdottir', 'Tunisia');
insert into companies (nombre, nacionalidad) values ('Harvey, Schinner and DuBuque', 'Mongolia');
insert into companies (nombre, nacionalidad) values ('Rosenbaum, Frami and Waters', 'South Africa');
insert into companies (nombre, nacionalidad) values ('Halvorson, Marvin and Nolan', 'Ecuador');
insert into companies (nombre, nacionalidad) values ('Mertz, Mayert and Schowalter', 'South Africa');
insert into companies (nombre, nacionalidad) values ('Jenkins, Johnson and MacGyver', 'Togo');
insert into companies (nombre, nacionalidad) values ('Pfeffer-Corwin', 'South Africa');
insert into companies (nombre, nacionalidad) values ('Streich-Watsica', 'Greece');
insert into companies (nombre, nacionalidad) values ('VonRueden, Nicolas and Littel', 'Azerbaijan');
insert into companies (nombre, nacionalidad) values ('Sipes-Kulas', 'Peru');
insert into companies (nombre, nacionalidad) values ('Heidenreich, Bernier and Fisher', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Leuschke, Hettinger and Bernhard', 'Paraguay');
insert into companies (nombre, nacionalidad) values ('Goodwin-Schaden', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Wyman, Nikolaus and Gerlach', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Schuppe-Boyer', 'Nigeria');
insert into companies (nombre, nacionalidad) values ('Tillman and Sons', 'China');
insert into companies (nombre, nacionalidad) values ('Franecki Group', 'Peru');
insert into companies (nombre, nacionalidad) values ('Jerde, Wolff and Runolfsdottir', 'China');
insert into companies (nombre, nacionalidad) values ('Heaney, Simonis and Bradtke', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Torp-Runolfsdottir', 'Russia');
insert into companies (nombre, nacionalidad) values ('Hand-Auer', 'Vietnam');
insert into companies (nombre, nacionalidad) values ('Gibson-Shields', 'United States');
insert into companies (nombre, nacionalidad) values ('Medhurst-Osinski', 'Germany');
insert into companies (nombre, nacionalidad) values ('Smitham-Tremblay', 'China');
insert into companies (nombre, nacionalidad) values ('Connelly Group', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Kulas-Anderson', 'Colombia');
insert into companies (nombre, nacionalidad) values ('Braun and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Koelpin-Deckow', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Boehm Inc', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Welch Inc', 'Cuba');
insert into companies (nombre, nacionalidad) values ('Fisher-Dickinson', 'Costa Rica');
insert into companies (nombre, nacionalidad) values ('Denesik Inc', 'Canada');
insert into companies (nombre, nacionalidad) values ('Pacocha, Williamson and Dibbert', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Grant, Grady and Hills', 'Russia');
insert into companies (nombre, nacionalidad) values ('Jacobs Group', 'Canada');
insert into companies (nombre, nacionalidad) values ('Yundt and Sons', 'Thailand');
insert into companies (nombre, nacionalidad) values ('Hayes Inc', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Kiehn-Kub', 'Poland');
insert into companies (nombre, nacionalidad) values ('Little and Sons', 'Indonesia');
insert into companies (nombre, nacionalidad) values ('Hintz-Gibson', 'Dominica');
insert into companies (nombre, nacionalidad) values ('Koepp-Rolfson', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Schowalter, Sawayn and Mayert', 'Japan');
insert into companies (nombre, nacionalidad) values ('Graham-Yost', 'China');
insert into companies (nombre, nacionalidad) values ('Waelchi, Stark and McLaughlin', 'Bangladesh');
insert into companies (nombre, nacionalidad) values ('Rippin, Bernhard and Lockman', 'Portugal');
insert into companies (nombre, nacionalidad) values ('Jacobs-Senger', 'Peru');
insert into companies (nombre, nacionalidad) values ('Corwin LLC', 'France');
insert into companies (nombre, nacionalidad) values ('Wehner Inc', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Kuhlman, Nolan and Walsh', 'South Korea');
insert into companies (nombre, nacionalidad) values ('Treutel, Stroman and Vandervort', 'United States');
insert into companies (nombre, nacionalidad) values ('Blick Group', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Gorczany, Huel and Waters', 'Poland');
insert into companies (nombre, nacionalidad) values ('Upton-Hettinger', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Kutch Group', 'China');
insert into companies (nombre, nacionalidad) values ('Harber-Schuster', 'Saint Kitts and Nevis');
insert into companies (nombre, nacionalidad) values ('Bartell Group', 'China');
insert into companies (nombre, nacionalidad) values ('Hansen, Heaney and Yost', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Cronin, Kris and Lubowitz', 'Comoros');
insert into companies (nombre, nacionalidad) values ('Lueilwitz, Effertz and Stiedemann', 'Russia');
insert into companies (nombre, nacionalidad) values ('Wunsch, Rempel and Gerlach', 'China');
insert into companies (nombre, nacionalidad) values ('Bartoletti, Ortiz and Vandervort', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Ullrich, Sauer and Williamson', 'Mexico');
insert into companies (nombre, nacionalidad) values ('Bergnaum-Schmidt', 'Philippines');
insert into companies (nombre, nacionalidad) values ('Rolfson Group', 'Brazil');
insert into companies (nombre, nacionalidad) values ('Gottlieb, Jast and Gibson', 'China');
